CREATE DATABASE walmart_data;
USE walmart_data;
CREATE TABLE walmart (
    Store INT,
    Date DATE,
    Weekly_Sales DECIMAL(10, 2),
    Holiday_Flag TINYINT,
    Temperature FLOAT,
    Fuel_Price FLOAT,
    CPI FLOAT,
    Unemployment FLOAT
);
SELECT * from walmart;

# 1. What was the total revenue generated by the retailer during the time period covered by the dataset?

SELECT SUM(Weekly_Sales) AS total_revenue
FROM walmart;

# 2. What is the average weekly sales across all stores?

SELECT AVG(Weekly_Sales) AS avg_weekly_sales
FROM walmart;

# 3. What is the average revenue per store?

SELECT Store, AVG(Weekly_Sales) AS avg_store_revenue
FROM walmart
GROUP BY Store;

# 4. Which store generated the highest total revenue?

SELECT Store, SUM(Weekly_Sales) AS total_revenue
FROM walmart
GROUP BY Store
ORDER BY total_revenue DESC
LIMIT 1;

# 5. Which store had the lowest total revenue?

SELECT Store, SUM(Weekly_Sales) AS total_revenue
FROM walmart
GROUP BY Store
ORDER BY total_revenue ASC
LIMIT 1;

# 6. What is the trend in total weekly sales over time (e.g., per month)?

SELECT
    DATE_FORMAT(STR_TO_DATE(Date, '%Y-%m-%d'), '%Y-%m') AS Month,
    SUM(Weekly_Sales) AS Total_Weekly_Sales
FROM Walmart
GROUP BY Month
ORDER BY Month;

# 7. How do sales differ between holiday and non-holiday weeks?

SELECT Holiday_Flag, AVG(Weekly_Sales) AS avg_sales
FROM walmart
GROUP BY Holiday_Flag;

# 8. What is the percentage contribution of each store to total revenue?

SELECT Store,
       ROUND(SUM(Weekly_Sales) * 100.0 / (SELECT SUM(Weekly_Sales) FROM walmart), 2) AS revenue_percentage
FROM walmart
GROUP BY Store
ORDER BY revenue_percentage DESC;

# 9. Which stores have shown consistent growth or decline in sales?

SELECT Store,
       DATE_FORMAT(STR_TO_DATE(Date, '%Y-%m-%d'), '%Y-%m') AS Month,
       SUM(Weekly_Sales) AS monthly_sales
FROM walmart
GROUP BY Store, month
ORDER BY Store, month;

# 10. What is the average sales per store per week?

SELECT Store, AVG(Weekly_Sales) AS avg_weekly_sales
FROM walmart
GROUP BY Store
ORDER BY avg_weekly_sales DESC;

# 11. Which store had the highest average sales per week?

SELECT Store, AVG(Weekly_Sales) AS avg_weekly_sales
FROM walmart
GROUP BY Store
ORDER BY avg_weekly_sales DESC
LIMIT 1;

# 12. Are there any seasonal patterns in sales for specific stores?

SELECT Store,
       EXTRACT(MONTH FROM Date) AS month,
       AVG(Weekly_Sales) AS avg_monthly_sales
FROM walmart
GROUP BY Store, month
ORDER BY Store, month;

# 13. What is the average sales during holiday weeks vs. non-holiday weeks?

SELECT Holiday_Flag, AVG(Weekly_Sales) AS avg_sales
FROM walmart
GROUP BY Holiday_Flag;

# 14. Which holiday weeks generated the most revenue?

SELECT Date, SUM(Weekly_Sales) AS total_sales
FROM walmart
WHERE Holiday_Flag = TRUE
GROUP BY Date
ORDER BY total_sales DESC
LIMIT 5;

# 15. How does sales performance change in the weeks leading up to and after holidays?

WITH holidays AS (
    SELECT DISTINCT Date
    FROM walmart
    WHERE Holiday_Flag = 1
),
sales_with_offset AS (
    SELECT 
        ws.Store,
        ws.Date,
        ws.Weekly_Sales,
        LAG(ws.Weekly_Sales) OVER (PARTITION BY ws.Store ORDER BY STR_TO_DATE(ws.Date, '%Y-%m-%d')) AS prev_week_sales,
        LEAD(ws.Weekly_Sales) OVER (PARTITION BY ws.Store ORDER BY STR_TO_DATE(ws.Date, '%Y-%m-%d')) AS next_week_sales
    FROM walmart ws
)
SELECT 
    s.Date,
    AVG(s.prev_week_sales) AS avg_prev_week_sales,
    AVG(s.Weekly_Sales) AS avg_holiday_week_sales,
    AVG(s.next_week_sales) AS avg_next_week_sales
FROM sales_with_offset s
JOIN holidays h ON s.Date = h.Date
GROUP BY s.Date
ORDER BY s.Date;
